name: Run Backtest Once

on:
  workflow_dispatch:

jobs:
  run-backtest:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install ccxt pandas numpy

      - name: Run Backtest
        run: |
          python BadTestClasificador.py

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: backtest-results
          path: backtest_take_drop.txt
